/**
 * qwrt Polyfill Build Script
 *
 * Bundles all polyfill modules into a single IIFE using esbuild,
 * then post-processes the output so `pal` is received as a closure
 * parameter from `__pal_inject__`.
 *
 * Strategy:
 *   1. Source code imports `pal` from `pal.js` which defines it as
 *      `var pal = globalThis.__pal_inject__`. This tells esbuild that
 *      `pal` is a defined module variable (not an undefined global),
 *      preventing it from being treated as an external.
 *   2. esbuild bundles with format:'iife' + globalName, producing:
 *      var qwrt_polyfill = (() => {
 *        var pal = globalThis.__pal_inject__;
 *        function setupConsole(pal2) { ... }  // renamed to avoid shadowing
 *        setupConsole(pal);
 *        ...
 *      })();
 *   3. Post-process:
 *      - Strip "var qwrt_polyfill = " prefix
 *      - Replace arrow IIFE with named function: (() => { ... })()
 *        becomes (function(pal) { ... })(__pal_inject__);
 *      - Remove "var pal = globalThis.__pal_inject__;" since pal
 *        now comes from the IIFE parameter
 *
 * Outputs:
 *   qwrt/src/polyfill_default.c  — compiled unit with default polyfill bytecode
 *   qwrt/dist/polyfill.bytecode  — raw bytecode file (for tests)
 *   (polyfill.js is a temporary file used as qjsc input, not for distribution)
 */

const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');
const DIST_DIR = path.join(ROOT_DIR, 'dist');
const ENTRY_POINT = path.join(__dirname, 'src', 'index.js');

// Ensure dist directory exists
if (!fs.existsSync(DIST_DIR)) {
  fs.mkdirSync(DIST_DIR, { recursive: true });
}

const isWatch = process.argv.includes('--watch');

// Common esbuild options
const esbuildOptions = {
  entryPoints: [ENTRY_POINT],
  bundle: true,
  format: 'iife',
  globalName: 'qwrt_polyfill',
  target: ['es2020'],
  minify: false,
};

/**
 * Post-process the esbuild IIFE output:
 *
 * Input (esbuild raw):
 *   var qwrt_polyfill = (() => {
 *     var pal = globalThis.__pal_inject__;
 *     ...
 *   })();
 *
 * Output (our wrapper):
 *   (function(pal) {
 *     ...
 *   })(__pal_inject__);
 */
function postProcess(js) {
  // 1. Strip "var qwrt_polyfill = " prefix
  js = js.replace(/^var qwrt_polyfill\s*=\s*/, '');

  // 2. Replace the arrow IIFE opening with a named function that takes `pal`
  //    After step 1, the string starts with: (() => {
  //    We need to replace that with: (function(pal) {
  //    Note: the outer ( is the IIFE invocation paren, () is the arrow params
  js = js.replace(/^\(\(\)\s*=>\s*\{/, '(function(pal) {');

  // 3. Replace the IIFE invocation: })();   =>   })(__pal_inject__);
  js = js.replace(/\}\)\(\)\s*;\s*$/, '})(__pal_inject__);\n');

  // 4. Remove the "var pal = globalThis.__pal_inject__;" line since
  //    pal is now provided by the IIFE parameter
  //    esbuild may output it with or without semicolons, various whitespace
  js = js.replace(/\s*var pal\s*=\s*globalThis\.__pal_inject__\s*;?\s*\n?/, '\n');

  return js;
}

if (isWatch) {
  // Watch mode — for development, writes raw output without post-processing
  esbuild.context({
    ...esbuildOptions,
    outfile: path.join(DIST_DIR, 'polyfill.js'),
    logLevel: 'info',
  }).then(ctx => {
    console.log('Note: Watch mode writes raw esbuild output. Run `npm run build` for post-processed output.');
    ctx.watch();
  }).catch(err => {
    console.error('Watch build failed:', err);
    process.exit(1);
  });
} else {
  // One-shot build
  const result = esbuild.buildSync({
    ...esbuildOptions,
    write: false,
  });

  // Get the bundled JS from esbuild output
  let js = result.outputFiles[0].text;

  // Post-process to inject pal as IIFE parameter
  js = postProcess(js);

  // Write polyfill.js (temporary file for qjsc input)
  const polyfillJsPath = path.join(DIST_DIR, 'polyfill.js');
  fs.writeFileSync(polyfillJsPath, js);

  // Generate bytecode using qjsc, then inline as C header
  const QJSC = process.env.QJSC || path.join(ROOT_DIR, '..', 'deps', 'quickjs-ng', 'build', 'qjsc');
  const bytecodePath = path.join(DIST_DIR, 'polyfill.bytecode');
  try {
    const { execSync } = require('child_process');
    execSync(QJSC + ' -C -b -o ' + bytecodePath + ' ' + polyfillJsPath, {
      stdio: 'pipe',
    });
    const bytecodeBytes = fs.readFileSync(bytecodePath);
    console.log('Compiled: ' + bytecodePath + ' (' + bytecodeBytes.length + ' bytes)');

    // Generate polyfill_default.c — compiled unit with default polyfill bytecode
    // Using a separate .c file avoids recompiling context.c on polyfill changes.
    let cSrc = '/* Auto-generated by polyfill/build.js — do not edit */\n';
    cSrc += '#include <stdint.h>\n';
    cSrc += '#include <stddef.h>\n\n';
    cSrc += 'const uint8_t qwrt_default_polyfill[] = {\n';

    for (let i = 0; i < bytecodeBytes.length; i++) {
      cSrc += '0x' + bytecodeBytes[i].toString(16).padStart(2, '0') + ',';
      if ((i + 1) % 16 === 0) {
        cSrc += '\n';
      }
    }

    cSrc += '\n};\n\n';
    cSrc += 'const size_t qwrt_default_polyfill_len = ' + bytecodeBytes.length + ';\n';

    const cPath = path.join(ROOT_DIR, 'src', 'polyfill_default.c');
    fs.writeFileSync(cPath, cSrc);
    console.log('Written: ' + cPath + ' (' + bytecodeBytes.length + ' bytes in array)');
  } catch (e) {
    console.error('Error: qjsc not found, cannot generate bytecode header: ' + e.message);
    process.exit(1);
  }
}
